sudo: required
dist: trusty

branches:
  only: master

cache:
  directories:
    - ./castlerole-ng/node_modules

before_install:
 - chmod +x ./Castlerole/mvnw



  

matrix:
  include:
    - language: java
      jdk: openjdk11
      addons:
        sonarcloud:
          organization: "castleroleprojectkey"
          token:
            secure: "c61961957613b0bd3a28fb8861dff3ac0ad98c61" # encrypted value of your token
      script:
        - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=AliAlFatly_castlerole

        # - mvn clean verify org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=AliAlFatly_castlerole
        # - ./mvnw test -B -q

        #- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent sonar-scanner -Dsonar.projectKey=AliAlFatly_castlerole
        #- sonar-scanner #-Pcoverage 
      before_script:
        - cd Castlerole

#----------------------------------------------------------------------------------------------------------------------------------------------

    - language: node_js
      node_js: stable
      addons:
        sonarcloud:
          organization: "castleroleprojectkey"
          token:
            secure: "6325e4ef4085a5568d1a0dded4b89aa50f84259e" # encrypted value of your token
      install:
        - npm install
      before_install:
        - cd castlerole-ng
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
      script:
        # - npm run build
        - ng test --watch=false --codeCoverage=true && ng lint && sonar-scanner
        #- ng test --watch=false --code-coverage 
        # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
        #- sonar-scanner #sonar.javascript.lcov.reportpaths=coverage/lcov.info #-Pcoverage -Dsonar.projectKey=castleroleprojectkey







# language: java
# jdk: 
#   openjdk11
# cache: npm
# before_install:
#  - chmod +x ./Castlerole/mvnw
# script: cd Castlerole && ./mvnw clean install test

  
# script: cd Castlerole && ./mvnw clean install test # ./Castlerole/mvnw clean install test #cd Castlerole && ./mvnw test -B # ./mvnw clean install test #
# script: 
#   - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox

#before_script: cd Castlerole && ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
# before_install:

# before_install:

# install: 


# language: java
# jdk:
#   - oraclejdk8
# script: cd common-dto-api && mvn install -Dmaven.compiler.target=8 -Dmaven.compiler.source=8 && cd ../com-turreta-soademo-configserver &&  mvn install -Dmaven.compiler.target=8 -Dmaven.compiler.source=8 && cd ../com-turreta-soademo-clientservice &&  mvn install -Dmaven.compiler.target=8 -Dmaven.compiler.source=8

# jobs:
#   include:
#     -stage: Test
#     script: ./mvnw clean test
# after_success:

# after_failure:

# after_script:

# before_deploy:

# deploy:

# after_deploy:

# notifications:
#   email: xxxxx


# addons:
#   sonarcloud:
#     organization: "castleroleprojectkey"
#     token:
#       secure: "**************************" # encrypted value of your token

# script:
#   # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
#   - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar