language: Java
jdk: 
  openjdk11



cache: npm

# before_install:

# install: 

# before_script: 

script: ./mvnw clean install

jobs:
  include:
    -stage: Test
    script: ./mvnw clean test
# after_success:

# after_failure:

# after_script:

# before_deploy:

# deploy:

# after_deploy:

# notifications:
#   email: xxxxx