language: java
jdk: 
  openjdk11



cache: npm

# before_install:

# install: 

# before_script: 
# before_install:
#   - chmod +x build.sh
  
script: cd Castlerole && ./mvnw install test #./Castlerole/mvnw clean install test



# language: java
# jdk:
#   - oraclejdk8
# script: cd common-dto-api && mvn install -Dmaven.compiler.target=8 -Dmaven.compiler.source=8 && cd ../com-turreta-soademo-configserver &&  mvn install -Dmaven.compiler.target=8 -Dmaven.compiler.source=8 && cd ../com-turreta-soademo-clientservice &&  mvn install -Dmaven.compiler.target=8 -Dmaven.compiler.source=8

# jobs:
#   include:
#     -stage: Test
#     script: ./mvnw clean test
# after_success:

# after_failure:

# after_script:

# before_deploy:

# deploy:

# after_deploy:

# notifications:
#   email: xxxxx