sudo: required
dist: trusty

branches:
  only: master

cache:
  directories:
    - ./castlerole-ng/node_modules


addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

matrix:
  include:
    - language: node_js
      node_js: stable
      install:
        - npm install
      before_install:
        - cd / && cd castlerole-ng
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
      script:
        - npm run build
    
    - language: java
      jdk: openjdk11
      script:
        - ./mvnw test -B -q
      before_script:
        - cd Castlerole








# language: java
# jdk: 
#   openjdk11
# cache: npm
# before_install:
#  - chmod +x ./Castlerole/mvnw
# script: cd Castlerole && ./mvnw clean install test

  
# script: cd Castlerole && ./mvnw clean install test # ./Castlerole/mvnw clean install test #cd Castlerole && ./mvnw test -B # ./mvnw clean install test #
# script: 
#   - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox

#before_script: cd Castlerole && ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
# before_install:

# before_install:

# install: 


# language: java
# jdk:
#   - oraclejdk8
# script: cd common-dto-api && mvn install -Dmaven.compiler.target=8 -Dmaven.compiler.source=8 && cd ../com-turreta-soademo-configserver &&  mvn install -Dmaven.compiler.target=8 -Dmaven.compiler.source=8 && cd ../com-turreta-soademo-clientservice &&  mvn install -Dmaven.compiler.target=8 -Dmaven.compiler.source=8

# jobs:
#   include:
#     -stage: Test
#     script: ./mvnw clean test
# after_success:

# after_failure:

# after_script:

# before_deploy:

# deploy:

# after_deploy:

# notifications:
#   email: xxxxx